In [1]:
import numpy as np
import sys

## The Basics

In [251]:
a=np.array([1,2,3],dtype='int64')
print(a)

[1 2 3]


In [252]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [253]:
print(a.ndim)
print(b.ndim)

1
2


In [254]:
print(a.shape)
b.shape

(3,)


(2, 3)

In [255]:
print(a.dtype)
b.dtype

int64


dtype('int64')

In [256]:
print(a.itemsize)
b.itemsize

8


8

In [257]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

24
24


### Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)


In [258]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [259]:
a[1,4]
a[1][4]
a[1][-3]

np.int64(12)

In [260]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [261]:
a[:,2]

array([ 3, 10])

In [262]:
a[0,1::2]

array([2, 4, 6])

In [263]:
a[1,4]=40
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 40, 13, 14]])

In [264]:
a[1,6]=60
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 40, 13, 60]])

In [265]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [266]:
# Get specific element(work outside in)
b[0,1,1]

np.int64(4)

#### Initializing Different Arrays (1s, 0s, full, random, etc...)

In [267]:
# All 0s matrix
x=np.zeros(5,dtype="int64")
x

array([0, 0, 0, 0, 0])

In [268]:
# All 1s matrix
z=np.ones((4,2,2),dtype="int")
z

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [269]:
# Any other numbers
np.full((9,9),99,dtype="float")

array([[99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.]])

In [270]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [271]:
np.random.rand(4,2,3)

array([[[0.91634402, 0.82945436, 0.07241331],
        [0.84334172, 0.11656173, 0.97430008]],

       [[0.63888226, 0.74262155, 0.37135459],
        [0.35359548, 0.54983491, 0.30014619]],

       [[0.45800597, 0.84035373, 0.38662026],
        [0.69279385, 0.38574943, 0.37346918]],

       [[0.3812839 , 0.81183435, 0.60549268],
        [0.0193494 , 0.82671411, 0.28646862]]])

In [272]:
np.random.random_sample(a.shape)

array([[0.45573974, 0.33952157, 0.4128005 , 0.81505139, 0.80853043,
        0.69591846, 0.82923103],
       [0.13961179, 0.25218875, 0.76409704, 0.10013961, 0.05349174,
        0.4569348 , 0.7673283 ]])

In [273]:
# Random Integer Values
np.random.randint(1000,size=(4,4))

array([[976, 209, 370, 589],
       [235, 631, 489, 258],
       [851, 579, 985, 580],
       [157, 985, 285, 873]], dtype=int32)

In [274]:
# The Identity Matrix
np.identity(7,dtype="int64")

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [275]:
# Repeat an array
a=np.array([[1,2,3]])
rl=np.repeat(a,3,axis=0)
rl

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [276]:
arr=np.ones((5,5),dtype="int64")
print(arr)
z=np.zeros((3,3),dtype="int64")
z[1,1]=9
print(z)
arr[1:4,1:4]=z
arr

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### Be careful when copying variables!!!!!

In [277]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]


In [278]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
# Look there is a difference between this one and the previous

[1 2 3]


### Basic Mathematics (arithmetic, trigonometry, etc.)

In [342]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [343]:
a+2

array([3, 4, 5, 6])

In [344]:
a-2

array([-1,  0,  1,  2])

In [345]:
a*2

array([2, 4, 6, 8])

In [346]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [348]:
b=np.array([1,0,1,0])
print(a+b)

[2 2 4 4]


In [349]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
print(np.sin(a)) # Take the sin
print(np.cos(a)) # Take the cosin
print(np.tan(a)) # Take the tan


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


### Linear Algebra

In [366]:
a=np.ones((2,3),dtype="int64")
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [ ]:
# Find the determinant of an identity matrix
c=np.identity(3)
np.linalg.det(c)


np.float64(1.0)

### Statistics

In [375]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [377]:
print(np.min(stats))
print(np.max(stats,axis=1))

1
[3 6]


In [380]:
np.sum(stats,axis=0)

array([5, 7, 9])

### Reorganizing Arrays (reshape, vstack, hstack)

In [382]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [398]:
# Vertically Stacking Vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [400]:
# Horizontal Stack
h1=np.ones((2,4),dtype=int)
h2=np.zeros((2,2),dtype=int)
np.hstack([h1,h2])

array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]])

### Load data in from a file

In [404]:
"""
filed_data=np.genfromtxt("",delimiter=",")
filed_data=filed_data.astype("int32")
filed_data
"""

'\nfiled_data=np.genfromtxt("",delimiter=",")\nfiled_data=filed_data.astype("int32")\nfiled_data\n'

### Advanced Indexing and Boolean Masking

In [414]:
nums=np.array([[10,20,30,40],[50,60,70,80]])
print(nums>50)
bool=nums[nums>30]
bool

[[False False False False]
 [False  True  True  True]]


array([40, 50, 60, 70, 80])

In [412]:
# You can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
print(np.any(nums>60,axis=0))
np.all(nums>60,axis=0)

[False  True]


array([False, False])

In [423]:
print(((nums>50) & (nums<100)))
print("-"*20)
(~(nums>50)&(nums<100))

[[False False False False]
 [False  True  True  True]]
--------------------


array([[ True,  True,  True,  True],
       [ True, False, False, False]])

In [ ]:
a=np.arange(1,31).reshape(6,5)
print(a[2:4,0:2])
print(a[[0,1,2,3],[1,2,3,4]])
print("-"*20)
print(a[[0,4,5],3:])

# StandWithPalestine 🍉

[[11 12]
 [16 17]]
[ 2  8 14 20]
--------------------
[[ 4  5]
 [24 25]
 [29 30]]
