In [11]:
import numpy as np
import sys

The Basics

In [12]:
a=np.array([1,2,3],dtype='int64')
print(a)

[1 2 3]


In [13]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
print(a.ndim)
print(b.ndim)

1
2


In [15]:
print(a.shape)
b.shape

(3,)


(2, 3)

In [16]:
print(a.dtype)
b.dtype

int64


dtype('int64')

In [17]:
print(a.itemsize)
b.itemsize

8


8

In [18]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

24
24


Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)


In [19]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a[1,4]
a[1][4]
a[1][-3]

np.int64(12)

In [21]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
a[:,2]

array([ 3, 10])

In [23]:
a[0,1::2]

array([2, 4, 6])

In [24]:
a[1,4]=40
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 40, 13, 14]])

In [28]:
a[1,6]=60
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 20, 40, 20, 60]])

In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [30]:
# Get specific element(work outside in)
b[0,1,1]

np.int64(4)

Initializing Different Arrays (1s, 0s, full, random, etc...)

In [35]:
# All 0s matrix
x=np.zeros(5,dtype="int64")
x

array([0, 0, 0, 0, 0])

In [39]:
# All 1s matrix
z=np.ones((4,2,2),dtype="int")
z

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [41]:
# Any other numbers
np.full((9,9),99,dtype="float")

array([[99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99.]])

In [43]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [114]:
np.random.rand(4,2,3)

array([[[0.46003158, 0.61634446, 0.51901633],
        [0.82306257, 0.0929671 , 0.16971334]],

       [[0.89368616, 0.15664169, 0.51314021],
        [0.06204477, 0.31958688, 0.10752957]],

       [[0.04737483, 0.76053085, 0.3894965 ],
        [0.75613028, 0.74728181, 0.83941828]],

       [[0.76505462, 0.23917159, 0.3125038 ],
        [0.13152781, 0.46064914, 0.29981904]]])

In [115]:
np.random.random_sample(a.shape)

array([[0.97163314, 0.83509933, 0.59500333, 0.97064186, 0.89737941,
        0.6792116 , 0.2347071 ],
       [0.97760233, 0.45388782, 0.04079326, 0.38281314, 0.42949997,
        0.39169472, 0.39133227]])

In [187]:
# Random Integer Values
np.random.randint(1000,size=(4,4))

array([[750, 206, 828, 590],
       [932, 848, 778, 929],
       [518,   5, 797, 852],
       [126, 691, 447, 450]], dtype=int32)

In [193]:
np.identity(7,dtype="int64")

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])